version: '3.7'
services:
  node:
    image: node:16-alpine
    user: "node"
    ports:
      - '9999:9999'
    working_dir: /app
    volumes:
      - ./gate-simulator/:/app
    command: "npm start"

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass